- hosts: localhost
  become: true
  gather_facts: true 
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: false
  tasks:
    - include: tasks/test.yml
    - include: tasks/packages.yml
    - include: tasks/docker.yml
    - include: tasks/tools.yml

