# https://dennisnotes.com/note/20180614-ubuntu-18.04-qemu-setup/
- name: QEMU KVM
  apt: name={{ item }} state=latest
  loop: [ 'qemu-kvm',  'bridge-utils', 'virt-manager', 'qemu', 'virt-viewer', 'spice-vdagent' ]
  #'libvirt-bin',  

  # - qemu-kvm 
  # - bridge-utils
  # - libvirt-daemon-system 
  # - libvirt-clients 
  # - virtinst  

  # - python-libvirt
  # - python-lxml
  # - cloud-image-utils
