# https://dennisnotes.com/note/20180614-ubuntu-18.04-qemu-setup/
- name: QEMU KVM
  apt: name={{ item }} state=latest
  loop: [ 'qemu-kvm',  'bridge-utils', 'virt-manager', 'qemu', 'virt-viewer', 'spice-vdagent' ]
  #'libvirt-bin',  

  # qemu - A generic machine emulator and virtualizer,
  # qemu-kvm - QEMU metapackage for KVM support (i.e. QEMU Full virtualization on x86 hardware),
  # libvirt-clients - programs for the libvirt library,
  # libvirt-daemon-system - Libvirt daemon configuration files,
  # virtinst - programs to create and clone virtual machines,
  # bridge-utils - utilities for configuring the Linux Ethernet bridge.
  # - python-libvirt
  # - python-lxml
  # - cloud-image-utils
  
