- name: Install packages 
  vars: 
    packages:
      - gparted 
      - udftools
      - remmina 
      - openssh-server
      - gnome-terminal
      - git
      - wget
  apt: 
    name: "{{ packages }}"