---

- name: Install packages 
  gather_facts: true 
  become: true
  tasks: 
    - name: Doing a ping
      ping:

    - name: Show info
      debug:
        msg: "Machine name: {{ ansible_hostname }}"