- name: Doing a ping
  ping:

- name: Show info
  debug:
    msg: "Machine {{ansible_hostname}}: {{ansible_distribution}} {{ansible_distribution_release}}"
  
- name: Show user
  debug:
    # Mostramos el usuario que se ha convertido en root
    msg: "{{ansible_env.SUDO_USER}}"